
trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: katalonTask@1
  displayName: 'Execute Katalon Studio project'
  inputs:
    version: '8.5.5'
    executeArgs: '-retry=0 -testSuitePath=""Test Suites/TS_RegressionTest" -browserType="Firefox (headless)" -executionProfile="default" -apiKey="2e52c062-c196-4f7a-80e8-3fb119068457" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=false -webui.autoUpdateDrivers=true'
